# Generated by Django 5.2.8 on 2025-11-14 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('portal_slug', models.SlugField(max_length=64, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#1D4ED8', max_length=7)),
                ('default_language', models.ForeignKey(db_column='default_language', default='en', on_delete=django.db.models.deletion.PROTECT, to='core.language', to_field='code')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='geo.indiastate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('role', models.CharField(default='doctor', max_length=32)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'clinic')},
            },
        ),
    ]
