# Generated by Django 5.2.8 on 2025-11-14 06:22

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(db_index=True, default=core.models.generate_public_id, editable=False, max_length=16, unique=True)),
                ('full_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('whatsapp_number', models.CharField(max_length=10, unique=True)),
                ('imc_number', models.CharField(max_length=32, unique=True)),
                ('clinic_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=10)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='geo.indiastate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('phone_number', models.CharField(db_index=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reps', to='brands.brand')),
            ],
            options={
                'unique_together': {('brand', 'phone_number')},
            },
        ),
    ]
