# Generated by Django 5.2.8 on 2025-11-18 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("campaigns", "0002_remove_registrationlink_campaign_and_more"),
        ("registration", "0002_alter_doctorregistration_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorregistration",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="doctorregistration",
            name="fieldrep",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.fieldrep",
            ),
        ),
        migrations.AddField(
            model_name="doctorregistration",
            name="registered_via",
            field=models.CharField(
                choices=[("self", "self"), ("fieldrep", "fieldrep")],
                default="self",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="registrationlink",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration_links",
                to="campaigns.campaign",
            ),
        ),
    ]
