# Generated by Django 5.2.8 on 2025-11-14 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('channel', models.CharField(choices=[('whatsapp', 'whatsapp'), ('email', 'email')], max_length=16)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'unique_together': {('key', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='MessageTemplateI18n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('language', models.ForeignKey(db_column='language', on_delete=django.db.models.deletion.PROTECT, to='core.language', to_field='code')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i18n', to='messaging.messagetemplate')),
            ],
            options={
                'unique_together': {('template', 'language')},
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_msisdn', models.CharField(db_index=True, max_length=10)),
                ('to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'whatsapp'), ('email', 'email')], max_length=16)),
                ('template_key', models.CharField(max_length=64)),
                ('body_rendered', models.TextField()),
                ('provider_message_id', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('status_meta', models.JSONField(blank=True, default=dict)),
                ('language', models.ForeignKey(db_column='language', on_delete=django.db.models.deletion.PROTECT, to='core.language', to_field='code')),
                ('share_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='sharing.shareevent')),
            ],
            options={
                'indexes': [models.Index(fields=['channel', 'status', 'created_at'], name='messaging_o_channel_bac2ea_idx')],
            },
        ),
    ]
