# Generated by Django 5.2.8 on 2025-11-21 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outboundmessage",
            name="to_email",
        ),
    ]
