# Generated by Django 5.2.8 on 2025-11-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_remove_outboundmessage_to_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundmessage",
            name="to_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="outboundmessage",
            name="to_msisdn",
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
    ]
