# Generated by Django 5.2.8 on 2025-11-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("messaging", "0003_outboundmessage_to_email_and_more"),
        (
            "sharing",
            "0002_remove_shareevent_campaign_remove_sharelink_campaign_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundmessage",
            name="dedupe_key",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name="outboundmessage",
            index=models.Index(
                fields=["provider_message_id"], name="messaging_o_provide_fab51b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outboundmessage",
            index=models.Index(
                fields=["dedupe_key"], name="messaging_o_dedupe__13fc3f_idx"
            ),
        ),
    ]
