# Generated by Django 5.2.8 on 2025-11-14 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('brands', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_doctors', models.PositiveIntegerField(default=0)),
                ('is_active_flag', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='brands.brand')),
                ('therapy_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='brands.therapyarea')),
            ],
            options={
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RegistrationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_self', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(default=0)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_links', to='campaigns.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignSubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_subtopics', to='campaigns.campaign')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='content.subtopic')),
            ],
            options={
                'unique_together': {('campaign', 'subtopic')},
            },
        ),
        migrations.CreateModel(
            name='DoctorCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tagged_at', models.DateTimeField(auto_now_add=True)),
                ('end_date_snapshot', models.DateField()),
                ('registered_via', models.CharField(choices=[('self', 'self'), ('fieldrep', 'fieldrep')], default='self', max_length=16)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_tags', to='campaigns.campaign')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_tags', to='accounts.doctor')),
                ('fieldrep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.fieldrep')),
            ],
            options={
                'unique_together': {('doctor', 'campaign')},
            },
        ),
    ]
