# Generated by Django 5.2.8 on 2025-11-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("brands", "0001_initial"),
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationlink",
            name="campaign",
        ),
        migrations.AlterField(
            model_name="doctorcampaign",
            name="registered_via",
            field=models.CharField(
                choices=[("self", "self"), ("fieldrep", "fieldrep")],
                default="fieldrep",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["start_date", "end_date"], name="campaigns_c_start_d_996cc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctorcampaign",
            index=models.Index(
                fields=["campaign", "tagged_at"], name="campaigns_d_campaig_820697_idx"
            ),
        ),
        migrations.DeleteModel(
            name="RegistrationLink",
        ),
    ]
