# Generated by Django 5.2.8 on 2025-11-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndiaState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('iso_code', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
