# Generated by Django 5.2.8 on 2025-11-14 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('default_thumbnail_url', models.URLField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('therapy_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtopics', to='brands.therapyarea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('title_en', models.CharField(max_length=256, unique=True)),
                ('keywords_en', models.TextField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='content.subtopic')),
            ],
        ),
        migrations.CreateModel(
            name='VideoI18n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_local', models.CharField(max_length=256)),
                ('keywords_local', models.TextField(blank=True, null=True)),
                ('youtube_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('language', models.ForeignKey(db_column='language', on_delete=django.db.models.deletion.PROTECT, to='core.language', to_field='code')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i18n', to='content.video')),
            ],
        ),
        migrations.CreateModel(
            name='SubtopicI18n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_local', models.CharField(max_length=256)),
                ('summary_local', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('language', models.ForeignKey(db_column='language', on_delete=django.db.models.deletion.PROTECT, to='core.language', to_field='code')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i18n', to='content.subtopic')),
            ],
            options={
                'unique_together': {('subtopic', 'language')},
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['title_en'], name='idx_video_title_en'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['sort_order'], name='idx_video_sort'),
        ),
        migrations.AddIndex(
            model_name='videoi18n',
            index=models.Index(fields=['title_local'], name='idx_videoi18n_title_local'),
        ),
        migrations.AlterUniqueTogether(
            name='videoi18n',
            unique_together={('video', 'language')},
        ),
    ]
