# Generated by Django 5.2.8 on 2025-11-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="video",
            name="idx_video_title_en",
        ),
        migrations.RemoveIndex(
            model_name="video",
            name="idx_video_sort",
        ),
        migrations.RemoveIndex(
            model_name="videoi18n",
            name="idx_videoi18n_title_local",
        ),
        migrations.AlterUniqueTogether(
            name="videoi18n",
            unique_together=set(),
        ),
    ]
