# Generated by Django 5.2.8 on 2025-11-14 06:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('clinics', '0001_initial'),
        ('content', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=24, unique=True)),
                ('type', models.CharField(choices=[('video', 'video'), ('subtopic', 'subtopic'), ('portal', 'portal')], max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.doctor')),
                ('language', models.ForeignKey(db_column='language', on_delete=django.db.models.deletion.PROTECT, to='core.language', to_field='code')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.subtopic')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.video')),
            ],
        ),
        migrations.CreateModel(
            name='ShareEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('video', 'video'), ('subtopic', 'subtopic'), ('portal', 'portal')], max_length=16)),
                ('patient_msisdn', models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')])),
                ('channel', models.CharField(choices=[('whatsapp', 'whatsapp'), ('email', 'email')], default='whatsapp', max_length=16)),
                ('message_preview', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.doctor')),
                ('language', models.ForeignKey(db_column='language', on_delete=django.db.models.deletion.PROTECT, to='core.language', to_field='code')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.subtopic')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.video')),
                ('share_link', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='share_event', to='sharing.sharelink')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referer', models.TextField(blank=True, null=True)),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='sharing.sharelink')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['type', 'clinic', 'language'], name='sharing_sha_type_133086_idx'),
        ),
    ]
