# Generated by Django 5.2.8 on 2025-11-21 06:39

import sharing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shareevent",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="sharelink",
            name="campaign",
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="token",
            field=models.CharField(
                db_index=True, default=sharing.models._token, max_length=32, unique=True
            ),
        ),
    ]
